### ISSUE TITLE
Could not update contact with privacy options in optinfields_civicrm_custom, contact your system administrator. Error from API Contact create: Found more than one Organisation with same Name.

### ISSUE THREAD

**Issue by aydun** [mattwire/uk.co.mjwconsult.optinfields#2]
I'm aware of issue #1 but i'll log this separately to avoid confusing the threads.

Doing a dedupe, using the 'name and email' rule on individuals, then selecting 'batch merge all duplicates'

18 pairs processed then produced the error in the title.  I used the 'skip' option to continue the dedupe and the rest succeeded.

```[info] $CRM_Queue_Page_AJAX_runNext_error = Exception: "Could not update contact with privacy options in optinfields_civicrm_custom, contact your system administrator. Error from API Contact create: Found more than one Organisation with same Name."
#0 /home/XXX/www/www/wp-includes/class-wp-hook.php(286): optinfields_civicrm_custom("edit", "12", "885", (Array:1))
#1 /home/XXX/www/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters("", (Array:4))
#2 /home/XXX/www/www/wp-includes/plugin.php(515): WP_Hook->do_action((Array:4))
#3 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(124): do_action_ref_array("civicrm_custom", (Array:4))
#4 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(98): CRM_Utils_Hook_WordPress->invokeViaUF(4, "edit", "12", "885", (Array:1), NULL, NULL, "civicrm_custom")
#5 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(184): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_custom", Object(Civi\Core\CiviEventDispatcher))
#6 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_custom", Object(Civi\Core\Event\GenericHookEvent))
#7 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_custom", Object(Civi\Core\Event\GenericHookEvent))
#8 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_custom", Object(Civi\Core\Event\GenericHookEvent))
#9 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(486): CRM_Utils_Hook->invoke((Array:4), "edit", "12", "885", (Array:1), NULL, NULL, "civicrm_custom")
#10 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomValueTable.php(273): CRM_Utils_Hook::custom("edit", "12", "885", (Array:1))
#11 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/BAO/CustomValueTable.php(380): CRM_Core_BAO_CustomValueTable::create((Array:1))
#12 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Contact.php(407): CRM_Core_BAO_CustomValueTable::store((Array:1), "civicrm_contact", "885")
#13 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Contact.php(2013): CRM_Contact_BAO_Contact::create((Array:16))
#14 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(1815): CRM_Contact_BAO_Contact::createProfileContact((Array:13), (Array:0), "885")
#15 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(2274): CRM_Dedupe_Merger::moveAllBelongings("885", "4971", (Array:16), TRUE)
#16 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(848): CRM_Dedupe_Merger::dedupePair((Array:16), (Array:2), (Array:0), "safe", TRUE, "885", "4971", "merge_Individual_1_0_0_3")
#17 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Dedupe/Merger.php(678): CRM_Dedupe_Merger::merge((Array:2), (Array:4), "safe", TRUE, TRUE)
#18 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Contact/Page/DedupeMerge.php(139): CRM_Dedupe_Merger::batchMerge("1", NULL, "safe", 2, 0, (Array:0), TRUE, FALSE)
#19 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Queue/Task.php(88): CRM_Contact_Page_DedupeMerge::callBatchMerge(Object(CRM_Queue_TaskContext), "1", NULL, "safe", 2, 0, (Array:0))
#20 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#21 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#22 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#23 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#24 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(275): CRM_Queue_Page_AJAX::runNext()
#25 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#26 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#27 /home/XXX/www/www/wp-content/plugins/civicrm/civicrm.php(1248): CRM_Core_Invoke::invoke((Array:4))
#28 /home/XXX/www/www/wp-includes/class-wp-hook.php(286): CiviCRM_For_WordPress->invoke("")
#29 /home/XXX/www/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters("", (Array:1))
#30 /home/XXX/www/www/wp-includes/plugin.php(453): WP_Hook->do_action((Array:1))
#31 /home/XXX/www/www/wp-admin/admin.php(224): do_action("toplevel_page_CiviCRM")
#32 {main}```

**Comment by mattwire** [comment]
Thanks @aydun I wonder if creating the custom fields on "Individuals" only would resolve this issue, or whether we need to add an additional check into optinfields_civicrm_custom (https://github.com/mattwire/uk.co.mjwconsult.optinfields/blob/master/optinfields.php#L141) to only act on individuals?

**Comment by aydun** [comment]
@mattwire The two contacts it was trying to merge are both Individuals so I'm not clear why it is trying to create an organisation.  I suspect the issue is caused by something in the `Contact.get` result at https://github.com/mattwire/uk.co.mjwconsult.optinfields/blob/master/optinfields.php#L154 being passed into the `Contact.create` at https://github.com/mattwire/uk.co.mjwconsult.optinfields/blob/master/optinfields.php#L201

Maybe construct a `$updateParams` with just the fields you need for the `Contact.create`
155:  `$updateParams = [ 'id' => $entity_id ];`
183:  `$updateParams['do_not_sms'] = $newValue;`
190:  `$updateParams['do_not_' . $privacyOption] = $newValue;`
201:  `civicrm_api3('Contact', 'create', $updateParams);`

**Comment by mattwire** [comment]
Now moved to https://lab.civicrm.org/extensions/optinfields - please re-open if this is still an issue
